{% set version = "0.1.3" %}

package:
  name: pymatsolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymatsolver/pymatsolver-{{ version }}.tar.gz
  sha256: a9dd23e4b44cdc5dc738b6f0375f2e5ced8a605a27f7fae891c1604de7a1b071

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pymkl >=0.0.3
    - scipy >=0.13
    - mumps

test:
  imports:
    - pymatsolver
    # This will be fixed in a new release.
    # - pymatsolver.mumps

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: 'pymatsolver: Matrix Solvers for Python'

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
