{% set name = "pymatsolver" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24b02d1022eaca2ec0199fa25052f5c0fa8ebee73ab26523c441385b4ece0651

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >=3.10
    - numpy >=1.21
    - scipy >=1.8
    - packaging
  run_constrained:
    - pydiso >=0.1
    - python-mumps >=0.0.2

test:
  imports:
    - pymatsolver
    - pymatsolver.solvers
    - pymatsolver.iterative
    - pymatsolver.wrappers
    - pymatsolver.direct
    - pymatsolver.direct.pardiso
    - pymatsolver.direct.mumps

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: "pymatsolver: Matrix Solvers for Python"

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
