{% set version = "0.2.0" %}

package:
  name: pymatsolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymatsolver/pymatsolver-{{ version }}.tar.gz
  sha256: df9e0444f3c7fadf57b226d7d90b7be1dea9e24718575b458ba50429736d6c45

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pydiso  # [not (osx and arm64)]
    - scipy

test:
  imports:
    - pymatsolver
  commands:
    # Testing explicitly that pydiso was referenced correctly
    - python -c "from pymatsolver import Pardiso"

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: "pymatsolver: Matrix Solvers for Python"

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
