{% set version = "0.2.0" %}

package:
  name: pymatsolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymatsolver/pymatsolver-{{ version }}.tar.gz
  sha256: df9e0444f3c7fadf57b226d7d90b7be1dea9e24718575b458ba50429736d6c45

build:
  number: 3

outputs:
  - name: pymatsolver-base
    build:
      script: "{{ PYTHON }} -m pip install . --no-deps -vv"
      noarch: python
    requirements:
      host:
        - python >= 3.7
        - pip
      run:
        - python >= 3.7
        - numpy
        - scipy
    test:
      imports:
        - pymatsolver

  - name: pymatsolver
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('pymatsolver-base', max_pin="x.x.x") }}
        - pydiso
    test:
      imports:
        - pymatsolver
      commands:
        - python -c "from pymatsolver import Pardiso"

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: "pymatsolver: Matrix Solvers for Python"

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
