{% set python_min = '3.11' %}
{% set name = "pymatsolver" %}
{% set version = "0.4.0" %}
{% set build_num = 1 %}

{% if default_direct is not defined %}
{% set default_direct = "none" %}
{% endif %}

{% if default_direct|string == "pardiso" %}
{% set build_num = build_num + 200 %}
{% elif default_direct|string == "mumps" %}
{% set build_num = build_num + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ef77e92ac5a780df08d921cc772e0fe230d88e114355eaa2958a2ffa5b35004

build:
  number: {{ build_num }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - scipy >=1.8
    - packaging
{% if default_direct|string == "pardiso" %}
    - pydiso >=0.1
{% elif default_direct|string == "mumps" %}
    - python-mumps >=0.0.2
{% endif %}
  run_constrained:
{% if default_direct|string != "pardiso" %}
    - pydiso >=0.1
{% endif %}
{% if default_direct|string != "mumps" %}
    - python-mumps >=0.0.2
{% endif %}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymatsolver
    - pymatsolver.solvers
    - pymatsolver.iterative
    - pymatsolver.wrappers
    - pymatsolver.direct
    - pymatsolver.direct.pardiso
    - pymatsolver.direct.mumps

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: "pymatsolver: Matrix Solvers for Python"

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
