{% set name = "pymatsolver" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3dd7451ae03f7fb663d1657c159592c62e5dd8e44e2aa4f5815894550032ccb

build:
  number: 0
  skip: true  # [py<310]

outputs:
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps -vv
      noarch: python

    requirements:
      host:
        - python
        - pip
        - setuptools >=64
        - setuptools_scm >=8
      run:
        - python >=3.10
        - numpy >=1.21
        - scipy >=1.8
        - packaging
      run_constrained:
        - pydiso >=0.1.0

    test:
      imports:
        - pymatsolver

  - name: {{ name }}
    build:
      noarch: python

    requirements:
      run:
        - {{ pin_subpackage(name+"-base", exact=True) }}
        - pydiso

    test:
      imports:
        - pymatsolver
      commands:
        - python -c "from pymatsolver import Pardiso"

about:
  home: http://simpeg.xyz/
  license: MIT
  license_file: LICENSE
  summary: "pymatsolver: Matrix Solvers for Python"

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
