travis:
  secure:
    BINSTAR_TOKEN: iqu7KO2xD0FXV0X7So0pd1qmeec9UTGT0wHiHcMxW1LX31Rj8BxEYnPm/2LS32ksUum7+q3jIXn/24CVHhhQw/yO+tMTqHVrOWPpBDmgrKnqqiwQjItO/s9kP6yGZ7PCHUNjivWy4QOnPlnTdNNwH6t1mCja666lYk9M/MARh8QOQ3LZWTN2WBDD+DXJfnSzKOXWqlwNc37P3rvfkEV+15LBfTEdqsuqUysx85JJmjXqu+Hfhs11gXxW/nQmaqXlssQPa4vAVDXB8eK4qUcILowQWv/z2kjJWth/IrxZy1xbzZ+GxQ9u20I8BT2fS/8KNEGD0S9+Qh0ATn/LSu7GvgMV5BfGfNKJ/5GAg5KmD7t8AHpW4pnqb8RjlIQDOTe8/OHveVbsyyoQAK+LoWoIWaUIHc0kvDeVHtumzMMzwzhxN4ZWzAsFUOHC3Ce47oxrWDrYDceP0nnzZEzMnpqQk350pR1TuwYDmLVfl1kvqHJeCwvU4YefbEI89aDE9PFqtR0wz6k7ajXNdcc/lQwbWmR8pyru+fvMv7wsDpz9ZaiZIT0EAe8rHVJzfr05OYFkgHMbCZJd5C1JoAqKhucMZJQZ4WO3XRq35kZyCINx6xwJ+tvALaipLZUVv+E/wlYYeBn8O8zcQGp+da4c51U61XBli3cIowXlhQ4aBeDcMpw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
